import type {
  App,
  User,
  Contract,
  Integration,
  AccessReviewCampaign,
  AccessReviewTask,
  Workflow,
  WorkflowRun,
  AuditEvent,
  UserAppAccess,
  Department,
  RiskScoringRule,
  NotificationPreference,
} from "./types"

// Helper to generate dates
const daysFromNow = (days: number) => {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString()
}

const daysAgo = (days: number) => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

const sources: Array<"okta" | "google" | "azure" | "manual" | "browser-extension"> = [
  "okta",
  "google",
  "azure",
  "manual",
  "browser-extension",
]

// Apps data (25 apps)
export const apps: App[] = [
  {
    id: "app-1",
    name: "Slack",
    vendor: "Salesforce",
    category: "Collaboration",
    description: "Team communication and collaboration platform",
    owner: "Sarah Chen",
    ownerId: "user-1",
    source: "okta",
    department: "Operations",
    monthlySpend: 12500,
    annualSpend: 150000,
    licensesPurchased: 500,
    licensesAssigned: 485,
    utilizationPercent: 97,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(45),
    status: "sanctioned",
    tags: ["core", "communication"],
    integrationsConnected: ["Okta", "Google Workspace"],
    adminCount: 5,
    oauthScopes: ["channels:read", "chat:write", "users:read"],
    permissions: ["Send messages", "Read channels", "Manage users"],
    notes: "Primary communication tool. Critical for all departments.",
    createdAt: daysAgo(730),
  },
  {
    id: "app-2",
    name: "GitHub Enterprise",
    vendor: "Microsoft",
    category: "DevTools",
    description: "Code hosting and version control",
    owner: "Mike Rodriguez",
    ownerId: "user-2",
    source: "okta",
    department: "Engineering",
    monthlySpend: 8500,
    annualSpend: 102000,
    licensesPurchased: 200,
    licensesAssigned: 195,
    utilizationPercent: 98,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(90),
    status: "sanctioned",
    tags: ["core", "development"],
    integrationsConnected: ["Okta", "Jira"],
    adminCount: 8,
    oauthScopes: ["repo", "admin:org", "workflow"],
    permissions: ["Repository access", "Organization admin", "Actions management"],
    notes: "Essential for all engineering teams.",
    createdAt: daysAgo(500),
  },
  {
    id: "app-3",
    name: "Salesforce",
    vendor: "Salesforce",
    category: "Sales",
    description: "CRM and sales automation platform",
    owner: "Jennifer Adams",
    ownerId: "user-3",
    source: "okta",
    department: "Sales",
    monthlySpend: 25000,
    annualSpend: 300000,
    licensesPurchased: 150,
    licensesAssigned: 142,
    utilizationPercent: 95,
    riskLevel: "medium",
    ssoConnected: true,
    lastActivity: daysAgo(1),
    renewalDate: daysFromNow(15),
    status: "sanctioned",
    tags: ["core", "sales"],
    integrationsConnected: ["Okta", "Slack"],
    adminCount: 4,
    oauthScopes: ["api", "full"],
    permissions: ["Full API access", "Customer data read/write"],
    notes: "Critical CRM. Renewal coming up - negotiate volume discount.",
    createdAt: daysAgo(900),
  },
  {
    id: "app-4",
    name: "Jira",
    vendor: "Atlassian",
    category: "DevTools",
    description: "Project tracking and issue management",
    owner: "Mike Rodriguez",
    ownerId: "user-2",
    source: "google",
    department: "Engineering",
    monthlySpend: 4200,
    annualSpend: 50400,
    licensesPurchased: 300,
    licensesAssigned: 278,
    utilizationPercent: 93,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(120),
    status: "sanctioned",
    tags: ["core", "project-management"],
    integrationsConnected: ["Okta", "Slack", "GitHub"],
    adminCount: 6,
    oauthScopes: ["read:jira-work", "write:jira-work"],
    permissions: ["Read issues", "Write issues", "Manage projects"],
    notes: "",
    createdAt: daysAgo(600),
  },
  {
    id: "app-5",
    name: "Figma",
    vendor: "Figma Inc.",
    category: "Collaboration",
    description: "Design and prototyping tool",
    owner: "Emily Watson",
    ownerId: "user-4",
    source: "okta",
    department: "Marketing",
    monthlySpend: 3800,
    annualSpend: 45600,
    licensesPurchased: 80,
    licensesAssigned: 75,
    utilizationPercent: 94,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(60),
    status: "sanctioned",
    tags: ["design", "collaboration"],
    integrationsConnected: ["Okta", "Slack"],
    adminCount: 3,
    oauthScopes: ["files:read", "files:write"],
    permissions: ["File access", "Team management"],
    notes: "Primary design tool for product and marketing teams.",
    createdAt: daysAgo(400),
  },
  {
    id: "app-6",
    name: "Notion",
    vendor: "Notion Labs",
    category: "Collaboration",
    description: "All-in-one workspace for notes and docs",
    owner: "Sarah Chen",
    ownerId: "user-1",
    source: "google",
    department: "Operations",
    monthlySpend: 2400,
    annualSpend: 28800,
    licensesPurchased: 200,
    licensesAssigned: 156,
    utilizationPercent: 78,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(1),
    renewalDate: daysFromNow(180),
    status: "sanctioned",
    tags: ["documentation", "collaboration"],
    integrationsConnected: ["Okta", "Slack"],
    adminCount: 4,
    oauthScopes: ["read_content", "update_content"],
    permissions: ["Read content", "Update content"],
    notes: "Consider seat optimization - 44 unused licenses.",
    createdAt: daysAgo(300),
  },
  {
    id: "app-7",
    name: "Zoom",
    vendor: "Zoom Video",
    category: "Collaboration",
    description: "Video conferencing platform",
    owner: "Sarah Chen",
    ownerId: "user-1",
    source: "okta",
    department: "Operations",
    monthlySpend: 5600,
    annualSpend: 67200,
    licensesPurchased: 400,
    licensesAssigned: 395,
    utilizationPercent: 99,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(200),
    status: "sanctioned",
    tags: ["core", "communication"],
    integrationsConnected: ["Okta", "Google Workspace", "Slack"],
    adminCount: 3,
    oauthScopes: ["meeting:read", "meeting:write", "user:read"],
    permissions: ["Meeting management", "User administration"],
    notes: "",
    createdAt: daysAgo(800),
  },
  {
    id: "app-8",
    name: "AWS",
    vendor: "Amazon",
    category: "DevTools",
    description: "Cloud infrastructure services",
    owner: "David Kim",
    ownerId: "user-5",
    source: "manual",
    department: "Engineering",
    monthlySpend: 45000,
    annualSpend: 540000,
    licensesPurchased: 100,
    licensesAssigned: 85,
    utilizationPercent: 85,
    riskLevel: "medium",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(365),
    status: "sanctioned",
    tags: ["core", "infrastructure"],
    integrationsConnected: ["Okta"],
    adminCount: 12,
    oauthScopes: ["iam:*", "ec2:*", "s3:*"],
    permissions: ["Full IAM access", "EC2 management", "S3 storage"],
    notes: "Largest spend item. Reserved instance savings opportunity.",
    createdAt: daysAgo(1000),
  },
  {
    id: "app-9",
    name: "Datadog",
    vendor: "Datadog Inc.",
    category: "DevTools",
    description: "Monitoring and analytics platform",
    owner: "David Kim",
    ownerId: "user-5",
    source: "okta",
    department: "Engineering",
    monthlySpend: 8200,
    annualSpend: 98400,
    licensesPurchased: 50,
    licensesAssigned: 48,
    utilizationPercent: 96,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(75),
    status: "sanctioned",
    tags: ["monitoring", "devops"],
    integrationsConnected: ["Okta", "Slack", "AWS"],
    adminCount: 5,
    oauthScopes: ["dashboards:read", "metrics:read"],
    permissions: ["Dashboard access", "Metrics read"],
    notes: "",
    createdAt: daysAgo(450),
  },
  {
    id: "app-10",
    name: "Workday",
    vendor: "Workday Inc.",
    category: "HR",
    description: "Human capital management",
    owner: "Lisa Thompson",
    ownerId: "user-6",
    source: "azure",
    department: "HR",
    monthlySpend: 18000,
    annualSpend: 216000,
    licensesPurchased: 500,
    licensesAssigned: 498,
    utilizationPercent: 100,
    riskLevel: "medium",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(25),
    status: "sanctioned",
    tags: ["core", "hr"],
    integrationsConnected: ["Okta", "NetSuite"],
    adminCount: 6,
    oauthScopes: ["worker:read", "compensation:read"],
    permissions: ["Worker data access", "Compensation data"],
    notes: "Renewal in 25 days - review contract terms.",
    createdAt: daysAgo(700),
  },
  {
    id: "app-11",
    name: "NetSuite",
    vendor: "Oracle",
    category: "Finance",
    description: "ERP and financial management",
    owner: "Robert Martinez",
    ownerId: "user-7",
    source: "azure",
    department: "Finance",
    monthlySpend: 22000,
    annualSpend: 264000,
    licensesPurchased: 80,
    licensesAssigned: 75,
    utilizationPercent: 94,
    riskLevel: "high",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(30),
    status: "sanctioned",
    tags: ["core", "finance"],
    integrationsConnected: ["Okta", "Workday"],
    adminCount: 4,
    oauthScopes: ["restlets", "suitetalk"],
    permissions: ["Financial data access", "Transaction management"],
    notes: "High risk due to financial data access. Audit scheduled.",
    createdAt: daysAgo(850),
  },
  {
    id: "app-12",
    name: "1Password Business",
    vendor: "1Password",
    category: "Security",
    description: "Password management",
    owner: "Alex Turner",
    ownerId: "user-8",
    source: "okta",
    department: "Engineering",
    monthlySpend: 1800,
    annualSpend: 21600,
    licensesPurchased: 500,
    licensesAssigned: 478,
    utilizationPercent: 96,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(150),
    status: "sanctioned",
    tags: ["security", "core"],
    integrationsConnected: ["Okta"],
    adminCount: 3,
    oauthScopes: ["vaults:read"],
    permissions: ["Vault access"],
    notes: "",
    createdAt: daysAgo(500),
  },
  {
    id: "app-13",
    name: "Okta",
    vendor: "Okta Inc.",
    category: "Security",
    description: "Identity and access management",
    owner: "Alex Turner",
    ownerId: "user-8",
    source: "manual",
    department: "Engineering",
    monthlySpend: 9500,
    annualSpend: 114000,
    licensesPurchased: 500,
    licensesAssigned: 498,
    utilizationPercent: 100,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(220),
    status: "sanctioned",
    tags: ["security", "core", "identity"],
    integrationsConnected: [],
    adminCount: 4,
    oauthScopes: ["okta.users.manage", "okta.apps.manage"],
    permissions: ["User management", "App management", "Policy control"],
    notes: "Core identity provider. Do not modify without security approval.",
    createdAt: daysAgo(900),
  },
  {
    id: "app-14",
    name: "Zendesk",
    vendor: "Zendesk Inc.",
    category: "Sales",
    description: "Customer support platform",
    owner: "Jennifer Adams",
    ownerId: "user-3",
    source: "google",
    department: "Sales",
    monthlySpend: 6800,
    annualSpend: 81600,
    licensesPurchased: 100,
    licensesAssigned: 92,
    utilizationPercent: 92,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(100),
    status: "sanctioned",
    tags: ["support", "customer-service"],
    integrationsConnected: ["Okta", "Slack", "Salesforce"],
    adminCount: 4,
    oauthScopes: ["tickets:read", "tickets:write", "users:read"],
    permissions: ["Ticket management", "User lookup"],
    notes: "",
    createdAt: daysAgo(600),
  },
  {
    id: "app-15",
    name: "Hubspot",
    vendor: "HubSpot Inc.",
    category: "Sales",
    description: "Marketing and sales automation",
    owner: "Jennifer Adams",
    ownerId: "user-3",
    source: "okta",
    department: "Sales",
    monthlySpend: 4500,
    annualSpend: 54000,
    licensesPurchased: 75,
    licensesAssigned: 68,
    utilizationPercent: 91,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(1),
    renewalDate: daysFromNow(140),
    status: "sanctioned",
    tags: ["marketing", "sales"],
    integrationsConnected: ["Okta", "Salesforce"],
    adminCount: 3,
    oauthScopes: ["contacts", "crm.objects.contacts.read"],
    permissions: ["Contact management", "CRM access"],
    notes: "",
    createdAt: daysAgo(400),
  },
  {
    id: "app-16",
    name: "Grammarly Business",
    vendor: "Grammarly Inc.",
    category: "Collaboration",
    description: "Writing assistance tool",
    owner: "Sarah Chen",
    ownerId: "user-1",
    source: "browser-extension",
    department: "Operations",
    monthlySpend: 1200,
    annualSpend: 14400,
    licensesPurchased: 200,
    licensesAssigned: 145,
    utilizationPercent: 73,
    riskLevel: "low",
    ssoConnected: false,
    lastActivity: daysAgo(3),
    renewalDate: daysFromNow(85),
    status: "sanctioned",
    tags: ["productivity"],
    integrationsConnected: [],
    adminCount: 2,
    oauthScopes: [],
    permissions: ["Text analysis"],
    notes: "Consider SSO integration. 55 unused licenses.",
    createdAt: daysAgo(200),
  },
  {
    id: "app-17",
    name: "Canva Enterprise",
    vendor: "Canva",
    category: "Collaboration",
    description: "Design platform for teams",
    owner: "Emily Watson",
    ownerId: "user-4",
    source: "google",
    department: "Marketing",
    monthlySpend: 900,
    annualSpend: 10800,
    licensesPurchased: 50,
    licensesAssigned: 32,
    utilizationPercent: 64,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(2),
    renewalDate: daysFromNow(200),
    status: "sanctioned",
    tags: ["design"],
    integrationsConnected: ["Okta"],
    adminCount: 2,
    oauthScopes: ["design:read", "design:write"],
    permissions: ["Design creation", "Asset management"],
    notes: "Low utilization - review at renewal.",
    createdAt: daysAgo(180),
  },
  {
    id: "app-18",
    name: "Airtable",
    vendor: "Airtable Inc.",
    category: "Collaboration",
    description: "Spreadsheet-database hybrid",
    owner: "Mike Rodriguez",
    ownerId: "user-2",
    source: "browser-extension",
    department: "Engineering",
    monthlySpend: 1600,
    annualSpend: 19200,
    licensesPurchased: 100,
    licensesAssigned: 67,
    utilizationPercent: 67,
    riskLevel: "medium",
    ssoConnected: false,
    lastActivity: daysAgo(1),
    renewalDate: daysFromNow(95),
    status: "under-review",
    tags: ["productivity", "database"],
    integrationsConnected: [],
    adminCount: 5,
    oauthScopes: ["data.records:read", "data.records:write"],
    permissions: ["Database access", "Record management"],
    notes: "Under review for SSO compliance. May contain sensitive data.",
    createdAt: daysAgo(250),
  },
  {
    id: "app-19",
    name: "Loom",
    vendor: "Loom Inc.",
    category: "Collaboration",
    description: "Video messaging for work",
    owner: "Sarah Chen",
    ownerId: "user-1",
    source: "okta",
    department: "Operations",
    monthlySpend: 800,
    annualSpend: 9600,
    licensesPurchased: 150,
    licensesAssigned: 89,
    utilizationPercent: 59,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(2),
    renewalDate: daysFromNow(170),
    status: "sanctioned",
    tags: ["video", "communication"],
    integrationsConnected: ["Okta", "Slack"],
    adminCount: 2,
    oauthScopes: ["videos:read"],
    permissions: ["Video access"],
    notes: "Very low utilization. Consider downgrading plan.",
    createdAt: daysAgo(300),
  },
  {
    id: "app-20",
    name: "Miro",
    vendor: "Miro Inc.",
    category: "Collaboration",
    description: "Visual collaboration platform",
    owner: "Emily Watson",
    ownerId: "user-4",
    source: "okta",
    department: "Marketing",
    monthlySpend: 2100,
    annualSpend: 25200,
    licensesPurchased: 100,
    licensesAssigned: 78,
    utilizationPercent: 78,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(110),
    status: "sanctioned",
    tags: ["collaboration", "whiteboard"],
    integrationsConnected: ["Okta", "Slack"],
    adminCount: 3,
    oauthScopes: ["boards:read", "boards:write"],
    permissions: ["Board access", "Collaboration"],
    notes: "",
    createdAt: daysAgo(350),
  },
  {
    id: "app-21",
    name: "Trello",
    vendor: "Atlassian",
    category: "Collaboration",
    description: "Kanban-style project boards",
    owner: "Mike Rodriguez",
    ownerId: "user-2",
    source: "browser-extension",
    department: "Engineering",
    monthlySpend: 500,
    annualSpend: 6000,
    licensesPurchased: 100,
    licensesAssigned: 45,
    utilizationPercent: 45,
    riskLevel: "low",
    ssoConnected: false,
    lastActivity: daysAgo(5),
    renewalDate: daysFromNow(50),
    status: "under-review",
    tags: ["project-management"],
    integrationsConnected: [],
    adminCount: 2,
    oauthScopes: ["read", "write"],
    permissions: ["Board access"],
    notes: "Duplicate functionality with Jira. Consider consolidation.",
    createdAt: daysAgo(400),
  },
  {
    id: "app-22",
    name: "Dropbox Business",
    vendor: "Dropbox Inc.",
    category: "Collaboration",
    description: "Cloud storage and file sharing",
    owner: "David Kim",
    ownerId: "user-5",
    source: "okta",
    department: "Engineering",
    monthlySpend: 3200,
    annualSpend: 38400,
    licensesPurchased: 200,
    licensesAssigned: 112,
    utilizationPercent: 56,
    riskLevel: "medium",
    ssoConnected: true,
    lastActivity: daysAgo(1),
    renewalDate: daysFromNow(20),
    status: "sanctioned",
    tags: ["storage", "file-sharing"],
    integrationsConnected: ["Okta"],
    adminCount: 3,
    oauthScopes: ["files.content.read", "files.content.write"],
    permissions: ["File access", "Sharing controls"],
    notes: "Low utilization. Renewal in 20 days - reduce seats.",
    createdAt: daysAgo(600),
  },
  {
    id: "app-23",
    name: "Postman",
    vendor: "Postman Inc.",
    category: "DevTools",
    description: "API development platform",
    owner: "David Kim",
    ownerId: "user-5",
    source: "okta",
    department: "Engineering",
    monthlySpend: 1500,
    annualSpend: 18000,
    licensesPurchased: 75,
    licensesAssigned: 68,
    utilizationPercent: 91,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(130),
    status: "sanctioned",
    tags: ["api", "development"],
    integrationsConnected: ["Okta"],
    adminCount: 2,
    oauthScopes: ["workspace:read"],
    permissions: ["Workspace access"],
    notes: "",
    createdAt: daysAgo(280),
  },
  {
    id: "app-24",
    name: "ChatGPT Enterprise",
    vendor: "OpenAI",
    category: "DevTools",
    description: "AI assistant for enterprise",
    owner: "Alex Turner",
    ownerId: "user-8",
    source: "manual",
    department: "Engineering",
    monthlySpend: 6000,
    annualSpend: 72000,
    licensesPurchased: 200,
    licensesAssigned: 185,
    utilizationPercent: 93,
    riskLevel: "high",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(280),
    status: "sanctioned",
    tags: ["ai", "productivity"],
    integrationsConnected: ["Okta"],
    adminCount: 3,
    oauthScopes: ["chat:read", "chat:write"],
    permissions: ["AI chat access", "Data processing"],
    notes: "High risk due to data handling. Usage policies in place.",
    createdAt: daysAgo(120),
  },
  {
    id: "app-25",
    name: "Linear",
    vendor: "Linear Inc.",
    category: "DevTools",
    description: "Issue tracking for software teams",
    owner: "Mike Rodriguez",
    ownerId: "user-2",
    source: "okta",
    department: "Engineering",
    monthlySpend: 1100,
    annualSpend: 13200,
    licensesPurchased: 80,
    licensesAssigned: 76,
    utilizationPercent: 95,
    riskLevel: "low",
    ssoConnected: true,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(160),
    status: "sanctioned",
    tags: ["issue-tracking", "development"],
    integrationsConnected: ["Okta", "Slack", "GitHub"],
    adminCount: 3,
    oauthScopes: ["issues:read", "issues:write"],
    permissions: ["Issue management", "Project access"],
    notes: "",
    createdAt: daysAgo(200),
  },
  {
    id: "app-26",
    name: "Calendly",
    vendor: "Calendly LLC",
    category: "Collaboration",
    description: "Scheduling automation",
    owner: "Unknown",
    ownerId: "",
    source: "browser-extension",
    department: "Sales",
    monthlySpend: 450,
    annualSpend: 5400,
    licensesPurchased: 30,
    licensesAssigned: 28,
    utilizationPercent: 93,
    riskLevel: "medium",
    ssoConnected: false,
    lastActivity: daysAgo(1),
    renewalDate: daysFromNow(45),
    status: "unsanctioned",
    tags: ["shadow-it", "scheduling"],
    integrationsConnected: [],
    adminCount: 1,
    oauthScopes: ["calendar:read", "calendar:write"],
    permissions: ["Calendar access"],
    notes: "Shadow IT - discovered via browser extension. Needs review.",
    createdAt: daysAgo(60),
  },
  {
    id: "app-27",
    name: "Monday.com",
    vendor: "Monday.com",
    category: "Collaboration",
    description: "Work management platform",
    owner: "Unknown",
    ownerId: "",
    source: "browser-extension",
    department: "Marketing",
    monthlySpend: 1200,
    annualSpend: 14400,
    licensesPurchased: 25,
    licensesAssigned: 22,
    utilizationPercent: 88,
    riskLevel: "high",
    ssoConnected: false,
    lastActivity: daysAgo(0),
    renewalDate: daysFromNow(30),
    status: "unsanctioned",
    tags: ["shadow-it", "project-management"],
    integrationsConnected: [],
    adminCount: 2,
    oauthScopes: [],
    permissions: ["Project data access"],
    notes: "Shadow IT - duplicate of Jira functionality. High risk due to no SSO.",
    createdAt: daysAgo(90),
  },
]

// Users data (60 users across 6 departments)
const departments = ["Engineering", "Sales", "Marketing", "Finance", "HR", "Operations"]
const avatars = [
  "/professional-headshot-1.png",
  "/professional-headshot-2.png",
  "/professional-headshot-3.png",
  "/professional-headshot-4.png",
]

export const users: User[] = [
  {
    id: "demo-admin",
    name: "IT Administrator",
    email: "admin@company.com",
    department: "IT",
    manager: "CTO",
    managerId: "",
    status: "active",
    appsUsed: 25,
    totalAppSpend: 15000,
    highRiskAccessCount: 0,
    lastActive: daysAgo(0),
    avatar: avatars[0],
    title: "IT Admin",
    startDate: daysAgo(1000),
    role: "IT_ADMIN",
  },
  {
    id: "demo-security",
    name: "Security Administrator",
    email: "security@company.com",
    department: "Security",
    manager: "CISO",
    managerId: "",
    status: "active",
    appsUsed: 18,
    totalAppSpend: 12000,
    highRiskAccessCount: 0,
    lastActive: daysAgo(0),
    avatar: avatars[1],
    title: "Security Admin",
    startDate: daysAgo(800),
    role: "SECURITY_ADMIN",
  },
  {
    id: "demo-finance",
    name: "Finance Administrator",
    email: "finance@company.com",
    department: "Finance",
    manager: "CFO",
    managerId: "",
    status: "active",
    appsUsed: 10,
    totalAppSpend: 8000,
    highRiskAccessCount: 0,
    lastActive: daysAgo(0),
    avatar: avatars[2],
    title: "Finance Admin",
    startDate: daysAgo(600),
    role: "FINANCE_ADMIN",
  },
  {
    id: "demo-readonly",
    name: "Demo User",
    email: "user@company.com",
    department: "Operations",
    manager: "VP Operations",
    managerId: "",
    status: "active",
    appsUsed: 5,
    totalAppSpend: 2000,
    highRiskAccessCount: 0,
    lastActive: daysAgo(0),
    avatar: avatars[3],
    title: "Analyst",
    startDate: daysAgo(300),
    role: "READ_ONLY",
  },
  // End demo users
  {
    id: "user-1",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    department: "Operations",
    manager: "CEO",
    managerId: "",
    status: "active",
    appsUsed: 12,
    totalAppSpend: 8500,
    highRiskAccessCount: 1,
    lastActive: daysAgo(0),
    avatar: avatars[0],
    title: "VP of Operations",
    startDate: daysAgo(900),
  },
  {
    id: "user-2",
    name: "Mike Rodriguez",
    email: "mike.rodriguez@company.com",
    department: "Engineering",
    manager: "CTO",
    managerId: "",
    status: "active",
    appsUsed: 15,
    totalAppSpend: 12000,
    highRiskAccessCount: 2,
    lastActive: daysAgo(0),
    avatar: avatars[1],
    title: "VP of Engineering",
    startDate: daysAgo(800),
  },
  {
    id: "user-3",
    name: "Jennifer Adams",
    email: "jennifer.adams@company.com",
    department: "Sales",
    manager: "CRO",
    managerId: "",
    status: "active",
    appsUsed: 10,
    totalAppSpend: 15000,
    highRiskAccessCount: 1,
    lastActive: daysAgo(0),
    avatar: avatars[2],
    title: "VP of Sales",
    startDate: daysAgo(700),
  },
  {
    id: "user-4",
    name: "Emily Watson",
    email: "emily.watson@company.com",
    department: "Marketing",
    manager: "CMO",
    managerId: "",
    status: "active",
    appsUsed: 8,
    totalAppSpend: 4200,
    highRiskAccessCount: 0,
    lastActive: daysAgo(0),
    avatar: avatars[3],
    title: "Design Lead",
    startDate: daysAgo(600),
  },
  {
    id: "user-5",
    name: "David Kim",
    email: "david.kim@company.com",
    department: "Engineering",
    manager: "Mike Rodriguez",
    managerId: "user-2",
    status: "active",
    appsUsed: 14,
    totalAppSpend: 18000,
    highRiskAccessCount: 3,
    lastActive: daysAgo(0),
    avatar: avatars[0],
    title: "Platform Lead",
    startDate: daysAgo(500),
  },
  {
    id: "user-6",
    name: "Lisa Thompson",
    email: "lisa.thompson@company.com",
    department: "HR",
    manager: "CHRO",
    managerId: "",
    status: "active",
    appsUsed: 6,
    totalAppSpend: 5500,
    highRiskAccessCount: 1,
    lastActive: daysAgo(0),
    avatar: avatars[1],
    title: "HR Director",
    startDate: daysAgo(750),
  },
  {
    id: "user-7",
    name: "Robert Martinez",
    email: "robert.martinez@company.com",
    department: "Finance",
    manager: "CFO",
    managerId: "",
    status: "active",
    appsUsed: 7,
    totalAppSpend: 9200,
    highRiskAccessCount: 2,
    lastActive: daysAgo(0),
    avatar: avatars[2],
    title: "Finance Director",
    startDate: daysAgo(650),
  },
  {
    id: "user-8",
    name: "Alex Turner",
    email: "alex.turner@company.com",
    department: "Engineering",
    manager: "Mike Rodriguez",
    managerId: "user-2",
    status: "active",
    appsUsed: 11,
    totalAppSpend: 7800,
    highRiskAccessCount: 2,
    lastActive: daysAgo(0),
    avatar: avatars[3],
    title: "Security Lead",
    startDate: daysAgo(550),
  },
]

// Generate additional users
for (let i = 9; i <= 60; i++) {
  const dept = departments[i % departments.length]
  const managers = users.filter(
    (u) => u.title.includes("VP") || u.title.includes("Director") || u.title.includes("Lead"),
  )
  const manager = managers[i % managers.length]
  const status: User["status"] = i % 15 === 0 ? "offboarding" : i % 12 === 0 ? "inactive" : "active"

  users.push({
    id: `user-${i}`,
    name: `Employee ${i}`,
    email: `employee${i}@company.com`,
    department: dept,
    manager: manager?.name || "",
    managerId: manager?.id || "",
    status,
    appsUsed: Math.floor(Math.random() * 12) + 3,
    totalAppSpend: Math.floor(Math.random() * 8000) + 1000,
    highRiskAccessCount: Math.floor(Math.random() * 3),
    lastActive:
      status === "inactive" ? daysAgo(Math.floor(Math.random() * 60) + 30) : daysAgo(Math.floor(Math.random() * 7)),
    avatar: avatars[i % avatars.length],
    title: `${dept} Specialist`,
    startDate: daysAgo(Math.floor(Math.random() * 700) + 100),
  })
}

// User app access data
export const userAppAccess: Record<string, UserAppAccess[]> = {}
users.forEach((user) => {
  const numApps = user.appsUsed
  const accessList: UserAppAccess[] = []
  const shuffledApps = [...apps].sort(() => Math.random() - 0.5).slice(0, numApps)

  shuffledApps.forEach((app) => {
    accessList.push({
      appId: app.id,
      appName: app.name,
      accessLevel: Math.random() > 0.8 ? "admin" : Math.random() > 0.5 ? "user" : "viewer",
      lastLogin:
        user.status === "inactive"
          ? daysAgo(Math.floor(Math.random() * 60) + 30)
          : daysAgo(Math.floor(Math.random() * 14)),
      licenseType: Math.random() > 0.7 ? "Premium" : "Standard",
      status: user.status === "inactive" ? "inactive" : "active",
    })
  })

  userAppAccess[user.id] = accessList
})

// Contracts data (15 contracts)
export const contracts: Contract[] = apps.slice(0, 15).map((app, i) => {
  const renewalDate = new Date(app.renewalDate)
  const daysUntilRenewal = Math.ceil((renewalDate.getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))

  // Determine renewal health based on days until renewal and auto-renew status
  let renewalHealth: "healthy" | "needs-review" | "at-risk" = "healthy"
  if (daysUntilRenewal <= 30 && !app.ssoConnected) {
    renewalHealth = "at-risk"
  } else if (daysUntilRenewal <= 60 || i % 5 === 0) {
    renewalHealth = "needs-review"
  }

  // Generate spend history for trend chart
  const spendHistory = Array.from({ length: 12 }, (_, monthIdx) => {
    const date = new Date()
    date.setMonth(date.getMonth() - (11 - monthIdx))
    const baseSpend = app.monthlySpend
    const variance = (Math.random() - 0.5) * baseSpend * 0.2
    return {
      month: date.toLocaleDateString("en-US", { month: "short", year: "2-digit" }),
      amount: Math.round(baseSpend + variance),
    }
  })

  const stakeholders = [
    {
      id: `stakeholder-${i}-1`,
      name: app.owner,
      role: "owner" as const,
      email: `${app.owner.toLowerCase().replace(" ", ".")}@company.com`,
    },
    { id: `stakeholder-${i}-2`, name: "Sarah Chen", role: "finance" as const, email: "sarah.chen@company.com" },
    { id: `stakeholder-${i}-3`, name: "Mike Johnson", role: "it" as const, email: "mike.johnson@company.com" },
  ]

  if (app.annualSpend > 50000) {
    stakeholders.push({
      id: `stakeholder-${i}-4`,
      name: "Legal Team",
      role: "legal" as const,
      email: "legal@company.com",
    })
  }

  return {
    id: `contract-${i + 1}`,
    appId: app.id,
    appName: app.name,
    vendor: app.vendor,
    contractValue: app.annualSpend,
    billingCadence: i % 3 === 0 ? "monthly" : i % 3 === 1 ? "quarterly" : "annual",
    termStart: daysAgo(365),
    termEnd: daysFromNow(Math.floor(Math.random() * 120) + 10),
    renewalDate: app.renewalDate,
    autoRenew: i % 4 !== 0,
    owner: app.owner,
    ownerId: app.ownerId,
    status: i < 3 ? "expiring" : i === 14 ? "expired" : "active",
    renewalHealth,
    stakeholders,
    documents: ["Master Agreement.pdf", "SOW.pdf", "DPA.pdf"],
    notes: i % 3 === 0 ? "Negotiating 10% discount for renewal" : "",
    spendHistory,
    terms: `This agreement is for the provision of ${app.name} services. The subscription includes ${app.licensesPurchased} user licenses with access to all standard features.`,
    paymentTerms: i % 2 === 0 ? "Net 30" : "Net 45",
    cancellationNotice: i % 3 === 0 ? 30 : i % 3 === 1 ? 60 : 90,
  }
})

// Integrations data (6 integrations)
export const integrations: Integration[] = [
  {
    id: "int-1",
    name: "Okta",
    description: "Identity and access management platform for secure authentication",
    icon: "shield",
    status: "connected",
    health: "healthy",
    lastSync: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 mins ago
    nextSync: new Date(Date.now() + 45 * 60 * 1000).toISOString(), // 45 mins from now
    permissionScopes: ["users.read", "users.manage", "apps.read", "apps.manage", "groups.read"],
    category: "identity",
    dataTypes: ["Users", "Groups", "Applications", "Login Events"],
    recordsIngested: 1247,
    errorMessage: null,
    syncHistory: [
      {
        id: "s1",
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 1247,
        duration: 45,
        errorMessage: null,
      },
      {
        id: "s2",
        timestamp: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 1245,
        duration: 42,
        errorMessage: null,
      },
      {
        id: "s3",
        timestamp: new Date(Date.now() - 135 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 1243,
        duration: 48,
        errorMessage: null,
      },
      {
        id: "s4",
        timestamp: new Date(Date.now() - 195 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 1240,
        duration: 44,
        errorMessage: null,
      },
      {
        id: "s5",
        timestamp: new Date(Date.now() - 255 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 1238,
        duration: 46,
        errorMessage: null,
      },
    ],
    config: { tenant: "acme.okta.com", syncInterval: 60 },
  },
  {
    id: "int-2",
    name: "Azure AD",
    description: "Microsoft identity platform for enterprise authentication",
    icon: "cloud",
    status: "disconnected",
    health: "unknown",
    lastSync: null,
    nextSync: null,
    permissionScopes: ["User.Read.All", "Directory.Read.All", "AuditLog.Read.All"],
    category: "identity",
    dataTypes: ["Users", "Groups", "Sign-in Logs"],
    recordsIngested: 0,
    errorMessage: null,
    syncHistory: [],
    config: {},
  },
  {
    id: "int-3",
    name: "Google Workspace",
    description: "Google productivity and collaboration suite",
    icon: "mail",
    status: "connected",
    health: "healthy",
    lastSync: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    nextSync: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    permissionScopes: [
      "admin.directory.user.readonly",
      "admin.directory.group.readonly",
      "admin.reports.audit.readonly",
    ],
    category: "identity",
    dataTypes: ["Users", "Groups", "Login Activity", "Drive Files"],
    recordsIngested: 892,
    errorMessage: null,
    syncHistory: [
      {
        id: "s1",
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 892,
        duration: 38,
        errorMessage: null,
      },
      {
        id: "s2",
        timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 890,
        duration: 35,
        errorMessage: null,
      },
      {
        id: "s3",
        timestamp: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
        status: "partial",
        recordsProcessed: 885,
        duration: 62,
        errorMessage: "Timeout fetching some drive metadata",
      },
    ],
    config: { domain: "acme.com", syncInterval: 60 },
  },
  {
    id: "int-4",
    name: "Slack",
    description: "Team communication and collaboration platform",
    icon: "message-square",
    status: "connected",
    health: "healthy",
    lastSync: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    nextSync: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
    permissionScopes: ["channels:read", "users:read", "chat:write", "team:read"],
    category: "communication",
    dataTypes: ["Users", "Channels", "App Installs"],
    recordsIngested: 156,
    errorMessage: null,
    syncHistory: [
      {
        id: "s1",
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 156,
        duration: 12,
        errorMessage: null,
      },
      {
        id: "s2",
        timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 155,
        duration: 11,
        errorMessage: null,
      },
    ],
    config: { workspace: "ACME Corp", syncInterval: 30 },
  },
  {
    id: "int-5",
    name: "Jira",
    description: "Issue tracking and agile project management",
    icon: "clipboard",
    status: "connected",
    health: "degraded",
    lastSync: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    nextSync: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    permissionScopes: ["read:jira-work", "write:jira-work", "read:jira-user"],
    category: "ticketing",
    dataTypes: ["Projects", "Issues", "Users"],
    recordsIngested: 3421,
    errorMessage: "API rate limit exceeded. Sync interval extended.",
    syncHistory: [
      {
        id: "s1",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        status: "partial",
        recordsProcessed: 3421,
        duration: 180,
        errorMessage: "Rate limited after 3421 records",
      },
      {
        id: "s2",
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        status: "failed",
        recordsProcessed: 0,
        duration: 5,
        errorMessage: "API rate limit exceeded",
      },
      {
        id: "s3",
        timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 3400,
        duration: 95,
        errorMessage: null,
      },
    ],
    config: { instance: "acme.atlassian.net", syncInterval: 180 },
  },
  {
    id: "int-6",
    name: "ServiceNow",
    description: "IT service management and workflow automation",
    icon: "settings",
    status: "connected",
    health: "healthy",
    lastSync: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    nextSync: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    permissionScopes: ["read_incidents", "read_requests", "read_users"],
    category: "ticketing",
    dataTypes: ["Incidents", "Requests", "Users", "Assets"],
    recordsIngested: 2156,
    errorMessage: null,
    syncHistory: [
      {
        id: "s1",
        timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 2156,
        duration: 67,
        errorMessage: null,
      },
      {
        id: "s2",
        timestamp: new Date(Date.now() - 105 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 2150,
        duration: 65,
        errorMessage: null,
      },
    ],
    config: { instance: "acme.service-now.com", syncInterval: 60 },
  },
  {
    id: "int-7",
    name: "NetSuite",
    description: "Enterprise resource planning and financial management",
    icon: "dollar-sign",
    status: "error",
    health: "unhealthy",
    lastSync: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    nextSync: null,
    permissionScopes: ["transactions.read", "vendors.read", "invoices.read"],
    category: "finance",
    dataTypes: ["Vendors", "Transactions", "Invoices"],
    recordsIngested: 845,
    errorMessage: "Authentication failed. OAuth token expired. Please reconnect the integration.",
    syncHistory: [
      {
        id: "s1",
        timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        status: "failed",
        recordsProcessed: 0,
        duration: 2,
        errorMessage: "OAuth token expired",
      },
      {
        id: "s2",
        timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 - 60 * 60 * 1000).toISOString(),
        status: "failed",
        recordsProcessed: 0,
        duration: 2,
        errorMessage: "OAuth token expired",
      },
      {
        id: "s3",
        timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 845,
        duration: 120,
        errorMessage: null,
      },
    ],
    config: { accountId: "12345", syncInterval: 360 },
  },
  {
    id: "int-8",
    name: "Expensify",
    description: "Expense management and receipt tracking",
    icon: "receipt",
    status: "connected",
    health: "healthy",
    lastSync: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    nextSync: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    permissionScopes: ["expenses.read", "reports.read", "users.read"],
    category: "finance",
    dataTypes: ["Expenses", "Reports", "Users"],
    recordsIngested: 1893,
    errorMessage: null,
    syncHistory: [
      {
        id: "s1",
        timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 1893,
        duration: 55,
        errorMessage: null,
      },
      {
        id: "s2",
        timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 1880,
        duration: 52,
        errorMessage: null,
      },
    ],
    config: { policyId: "ACME-2024", syncInterval: 360 },
  },
  {
    id: "int-9",
    name: "Browser Extension",
    description: "Shadow IT discovery via browser activity monitoring",
    icon: "globe",
    status: "connected",
    health: "healthy",
    lastSync: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    nextSync: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    permissionScopes: ["browser.history.read", "browser.tabs.read"],
    category: "other",
    dataTypes: ["Visited SaaS Apps", "Login Events"],
    recordsIngested: 47,
    errorMessage: null,
    syncHistory: [
      {
        id: "s1",
        timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 47,
        duration: 3,
        errorMessage: null,
      },
      {
        id: "s2",
        timestamp: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
        status: "success",
        recordsProcessed: 45,
        duration: 3,
        errorMessage: null,
      },
    ],
    config: { enrolledDevices: 156, syncInterval: 5 },
  },
]

// Access Review Campaigns
export const accessReviewCampaigns: AccessReviewCampaign[] = [
  {
    id: "campaign-1",
    name: "Q4 2024 Access Review",
    description: "Quarterly review of all high-risk application access",
    scope: { apps: ["app-8", "app-11", "app-24"], departments: [] },
    dueDate: daysFromNow(14),
    completionPercent: 65,
    reviewers: ["Sarah Chen", "Alex Turner"],
    status: "active",
    createdAt: daysAgo(21),
    tasksTotal: 45,
    tasksCompleted: 29,
  },
  {
    id: "campaign-2",
    name: "Finance Apps Review",
    description: "Annual review of finance application access for SOC 2 compliance",
    scope: { apps: [], departments: ["Finance"] },
    dueDate: daysFromNow(30),
    completionPercent: 25,
    reviewers: ["Robert Martinez", "Lisa Thompson"],
    status: "active",
    createdAt: daysAgo(7),
    tasksTotal: 32,
    tasksCompleted: 8,
  },
  {
    id: "campaign-3",
    name: "Q3 2024 Access Review",
    description: "Completed quarterly review",
    scope: { apps: [], departments: ["Engineering", "Sales"] },
    dueDate: daysAgo(30),
    completionPercent: 100,
    reviewers: ["Mike Rodriguez", "Jennifer Adams"],
    status: "completed",
    createdAt: daysAgo(60),
    tasksTotal: 78,
    tasksCompleted: 78,
  },
  {
    id: "campaign-4",
    name: "AWS Admin Access Audit",
    description: "Critical review of AWS administrative privileges",
    scope: { apps: ["app-24"], departments: [] },
    dueDate: daysAgo(5),
    completionPercent: 40,
    reviewers: ["Sarah Chen"],
    status: "overdue",
    createdAt: daysAgo(35),
    tasksTotal: 15,
    tasksCompleted: 6,
  },
  {
    id: "campaign-5",
    name: "Q1 2025 Preparation",
    description: "Draft campaign for upcoming quarterly review",
    scope: { apps: [], departments: ["Engineering", "Product", "Design"] },
    dueDate: daysFromNow(60),
    completionPercent: 0,
    reviewers: ["Alex Turner", "Lisa Thompson"],
    status: "draft",
    createdAt: daysAgo(2),
    tasksTotal: 0,
    tasksCompleted: 0,
  },
  {
    id: "campaign-6",
    name: "Salesforce Access Review",
    description: "Annual review of Salesforce licenses and permissions",
    scope: { apps: ["app-5"], departments: ["Sales", "Marketing"] },
    dueDate: daysFromNow(7),
    completionPercent: 80,
    reviewers: ["Robert Martinez"],
    status: "active",
    createdAt: daysAgo(28),
    tasksTotal: 24,
    tasksCompleted: 19,
  },
]

// Access Review Tasks
export const accessReviewTasks: AccessReviewTask[] = [
  // Campaign 1 tasks
  {
    id: "task-1",
    campaignId: "campaign-1",
    userId: "user-1",
    userName: "Sarah Chen",
    userEmail: "sarah.chen@company.com",
    userDepartment: "Engineering",
    appId: "app-8",
    appName: "Splunk",
    accessLevel: "admin",
    lastLogin: daysAgo(2),
    riskLevel: "high",
    unusedAccess: false,
    decision: "approved",
    decidedBy: "Alex Turner",
    decidedAt: daysAgo(5),
    rationale: "Access required for security monitoring duties",
  },
  {
    id: "task-2",
    campaignId: "campaign-1",
    userId: "user-5",
    userName: "Emily Watson",
    userEmail: "emily.watson@company.com",
    userDepartment: "Sales",
    appId: "app-11",
    appName: "Datadog",
    accessLevel: "viewer",
    lastLogin: daysAgo(45),
    riskLevel: "medium",
    unusedAccess: true,
    decision: "pending",
    decidedBy: null,
    decidedAt: null,
    rationale: "",
  },
  {
    id: "task-3",
    campaignId: "campaign-1",
    userId: "user-12",
    userName: "Alex Turner",
    userEmail: "alex.turner@company.com",
    userDepartment: "Engineering",
    appId: "app-24",
    appName: "AWS",
    accessLevel: "admin",
    lastLogin: daysAgo(1),
    riskLevel: "critical",
    unusedAccess: false,
    decision: "pending",
    decidedBy: null,
    decidedAt: null,
    rationale: "",
  },
  {
    id: "task-4",
    campaignId: "campaign-1",
    userId: "user-8",
    userName: "Robert Martinez",
    userEmail: "robert.martinez@company.com",
    userDepartment: "Finance",
    appId: "app-8",
    appName: "Splunk",
    accessLevel: "user",
    lastLogin: daysAgo(90),
    riskLevel: "low",
    unusedAccess: true,
    decision: "revoked",
    decidedBy: "Sarah Chen",
    decidedAt: daysAgo(3),
    rationale: "No access in 90+ days, removing unused license",
  },
  {
    id: "task-5",
    campaignId: "campaign-1",
    userId: "user-15",
    userName: "Lisa Thompson",
    userEmail: "lisa.thompson@company.com",
    userDepartment: "HR",
    appId: "app-11",
    appName: "Datadog",
    accessLevel: "user",
    lastLogin: daysAgo(30),
    riskLevel: "low",
    unusedAccess: false,
    decision: "pending",
    decidedBy: null,
    decidedAt: null,
    rationale: "",
  },
  // Campaign 2 tasks
  {
    id: "task-6",
    campaignId: "campaign-2",
    userId: "user-8",
    userName: "Robert Martinez",
    userEmail: "robert.martinez@company.com",
    userDepartment: "Finance",
    appId: "app-6",
    appName: "NetSuite",
    accessLevel: "admin",
    lastLogin: daysAgo(1),
    riskLevel: "high",
    unusedAccess: false,
    decision: "approved",
    decidedBy: "Lisa Thompson",
    decidedAt: daysAgo(2),
    rationale: "CFO requires full admin access",
  },
  {
    id: "task-7",
    campaignId: "campaign-2",
    userId: "user-22",
    userName: "Jennifer Adams",
    userEmail: "jennifer.adams@company.com",
    userDepartment: "Finance",
    appId: "app-6",
    appName: "NetSuite",
    accessLevel: "user",
    lastLogin: daysAgo(3),
    riskLevel: "medium",
    unusedAccess: false,
    decision: "pending",
    decidedBy: null,
    decidedAt: null,
    rationale: "",
  },
  {
    id: "task-8",
    campaignId: "campaign-2",
    userId: "user-33",
    userName: "David Kim",
    userEmail: "david.kim@company.com",
    userDepartment: "Finance",
    appId: "app-7",
    appName: "Expensify",
    accessLevel: "approver",
    lastLogin: daysAgo(7),
    riskLevel: "medium",
    unusedAccess: false,
    decision: "pending",
    decidedBy: null,
    decidedAt: null,
    rationale: "",
  },
  // Campaign 4 (overdue) tasks
  {
    id: "task-9",
    campaignId: "campaign-4",
    userId: "user-1",
    userName: "Sarah Chen",
    userEmail: "sarah.chen@company.com",
    userDepartment: "Engineering",
    appId: "app-24",
    appName: "AWS",
    accessLevel: "admin",
    lastLogin: daysAgo(1),
    riskLevel: "critical",
    unusedAccess: false,
    decision: "approved",
    decidedBy: "Sarah Chen",
    decidedAt: daysAgo(10),
    rationale: "Infrastructure lead requires admin access",
  },
  {
    id: "task-10",
    campaignId: "campaign-4",
    userId: "user-45",
    userName: "Former Employee",
    userEmail: "former.employee@company.com",
    userDepartment: "Engineering",
    appId: "app-24",
    appName: "AWS",
    accessLevel: "admin",
    lastLogin: daysAgo(120),
    riskLevel: "critical",
    unusedAccess: true,
    decision: "pending",
    decidedBy: null,
    decidedAt: null,
    rationale: "",
  },
  // Campaign 6 tasks
  {
    id: "task-11",
    campaignId: "campaign-6",
    userId: "user-5",
    userName: "Emily Watson",
    userEmail: "emily.watson@company.com",
    userDepartment: "Sales",
    appId: "app-5",
    appName: "Salesforce",
    accessLevel: "user",
    lastLogin: daysAgo(1),
    riskLevel: "low",
    unusedAccess: false,
    decision: "approved",
    decidedBy: "Robert Martinez",
    decidedAt: daysAgo(7),
    rationale: "Active sales rep",
  },
  {
    id: "task-12",
    campaignId: "campaign-6",
    userId: "user-28",
    userName: "Marketing Intern",
    userEmail: "intern@company.com",
    userDepartment: "Marketing",
    appId: "app-5",
    appName: "Salesforce",
    accessLevel: "viewer",
    lastLogin: daysAgo(60),
    riskLevel: "low",
    unusedAccess: true,
    decision: "pending",
    decidedBy: null,
    decidedAt: null,
    rationale: "",
  },
]

// Workflows
export const workflows: Workflow[] = [
  {
    id: "wf-1",
    name: "Employee Onboarding",
    description: "Automated provisioning for new employees",
    type: "onboarding",
    status: "active",
    trigger: { type: "user-created", config: {} },
    steps: [
      { id: "s1", type: "create-ticket", name: "Create IT ticket", config: { system: "Jira" }, order: 1 },
      { id: "s2", type: "slack-notify", name: "Notify manager", config: { channel: "#new-hires" }, order: 2 },
      { id: "s3", type: "request-approval", name: "Get app access approval", config: {}, order: 3 },
    ],
    createdAt: daysAgo(180),
    lastRun: daysAgo(2),
    runCount: 45,
  },
  {
    id: "wf-2",
    name: "Employee Offboarding",
    description: "Automated deprovisioning for departing employees",
    type: "offboarding",
    status: "active",
    trigger: { type: "user-deactivated", config: {} },
    steps: [
      { id: "s1", type: "deprovision", name: "Revoke all access", config: {}, order: 1 },
      { id: "s2", type: "reclaim-license", name: "Reclaim licenses", config: {}, order: 2 },
      { id: "s3", type: "create-ticket", name: "Create offboarding ticket", config: { system: "Jira" }, order: 3 },
      { id: "s4", type: "slack-notify", name: "Notify IT team", config: { channel: "#it-ops" }, order: 4 },
    ],
    createdAt: daysAgo(180),
    lastRun: daysAgo(5),
    runCount: 23,
  },
  {
    id: "wf-3",
    name: "Seat Reclamation",
    description: "Reclaim unused licenses after inactivity",
    type: "seat-reclamation",
    status: "active",
    trigger: { type: "inactivity", config: { days: 30 } },
    steps: [
      { id: "s1", type: "slack-notify", name: "Warn user", config: { template: "inactivity-warning" }, order: 1 },
      { id: "s2", type: "wait", name: "Wait 7 days", config: { days: 7 }, order: 2 },
      { id: "s3", type: "reclaim-license", name: "Reclaim license", config: {}, order: 3 },
      { id: "s4", type: "create-ticket", name: "Log reclamation", config: { system: "Jira" }, order: 4 },
    ],
    createdAt: daysAgo(90),
    lastRun: daysAgo(1),
    runCount: 67,
  },
  {
    id: "wf-4",
    name: "Renewal Reminder",
    description: "Notify stakeholders of upcoming renewals",
    type: "renewal-reminder",
    status: "active",
    trigger: { type: "renewal-window", config: { days: 60 } },
    steps: [
      { id: "s1", type: "slack-notify", name: "Notify owner", config: {}, order: 1 },
      { id: "s2", type: "create-ticket", name: "Create renewal ticket", config: { system: "Jira" }, order: 2 },
    ],
    createdAt: daysAgo(120),
    lastRun: daysAgo(3),
    runCount: 34,
  },
  {
    id: "wf-5",
    name: "Shadow IT Alert",
    description: "Alert on unsanctioned app detection",
    type: "access-request",
    status: "active",
    trigger: { type: "unsanctioned-app", config: {} },
    steps: [
      {
        id: "s1",
        type: "slack-notify",
        name: "Alert security team",
        config: { channel: "#security-alerts" },
        order: 1,
      },
      { id: "s2", type: "create-ticket", name: "Create review ticket", config: { system: "Jira" }, order: 2 },
    ],
    createdAt: daysAgo(60),
    lastRun: daysAgo(7),
    runCount: 12,
  },
]

// Workflow Runs
export const workflowRuns: WorkflowRun[] = [
  {
    id: "run-1",
    workflowId: "wf-1",
    workflowName: "Employee Onboarding",
    status: "success",
    startedAt: daysAgo(2),
    completedAt: daysAgo(2),
    triggeredBy: "System",
    logs: [
      { timestamp: daysAgo(2), step: "Create IT ticket", status: "success", message: "Ticket JIRA-1234 created" },
      { timestamp: daysAgo(2), step: "Notify manager", status: "success", message: "Slack notification sent" },
      {
        timestamp: daysAgo(2),
        step: "Get app access approval",
        status: "success",
        message: "Approval granted by Mike Rodriguez",
      },
    ],
  },
  {
    id: "run-2",
    workflowId: "wf-3",
    workflowName: "Seat Reclamation",
    status: "success",
    startedAt: daysAgo(1),
    completedAt: daysAgo(1),
    triggeredBy: "System",
    logs: [
      {
        timestamp: daysAgo(1),
        step: "Warn user",
        status: "success",
        message: "Warning sent to employee45@company.com",
      },
      { timestamp: daysAgo(1), step: "Wait 7 days", status: "skipped", message: "User remained inactive" },
      { timestamp: daysAgo(1), step: "Reclaim license", status: "success", message: "Figma license reclaimed" },
      { timestamp: daysAgo(1), step: "Log reclamation", status: "success", message: "Ticket JIRA-1245 created" },
    ],
  },
  {
    id: "run-3",
    workflowId: "wf-2",
    workflowName: "Employee Offboarding",
    status: "failed",
    startedAt: daysAgo(5),
    completedAt: daysAgo(5),
    triggeredBy: "System",
    logs: [
      { timestamp: daysAgo(5), step: "Revoke all access", status: "success", message: "Access revoked for 8 apps" },
      {
        timestamp: daysAgo(5),
        step: "Reclaim licenses",
        status: "failed",
        message: "Failed to reclaim Salesforce license - API error",
      },
      {
        timestamp: daysAgo(5),
        step: "Create offboarding ticket",
        status: "skipped",
        message: "Skipped due to previous failure",
      },
      { timestamp: daysAgo(5), step: "Notify IT team", status: "skipped", message: "Skipped due to previous failure" },
    ],
  },
  {
    id: "run-4",
    workflowId: "wf-4",
    workflowName: "Renewal Reminder",
    status: "success",
    startedAt: daysAgo(3),
    completedAt: daysAgo(3),
    triggeredBy: "System",
    logs: [
      {
        timestamp: daysAgo(3),
        step: "Notify owner",
        status: "success",
        message: "Notified Jennifer Adams about Salesforce renewal",
      },
      { timestamp: daysAgo(3), step: "Create renewal ticket", status: "success", message: "Ticket JIRA-1240 created" },
    ],
  },
]

// Audit Events
export const auditEvents: AuditEvent[] = [
  {
    id: "audit-1",
    entityType: "app",
    entityId: "app-3",
    entityName: "Salesforce",
    action: "status_changed",
    actor: "Sarah Chen",
    actorId: "user-1",
    timestamp: daysAgo(1),
    details: { from: "under-review", to: "sanctioned" },
  },
  {
    id: "audit-2",
    entityType: "user",
    entityId: "user-45",
    entityName: "Employee 45",
    action: "license_reclaimed",
    actor: "System",
    actorId: "",
    timestamp: daysAgo(1),
    details: { app: "Figma", reason: "inactivity" },
  },
  {
    id: "audit-3",
    entityType: "app",
    entityId: "app-18",
    entityName: "Airtable",
    action: "status_changed",
    actor: "Alex Turner",
    actorId: "user-8",
    timestamp: daysAgo(3),
    details: { from: "sanctioned", to: "under-review" },
  },
  {
    id: "audit-4",
    entityType: "access-review",
    entityId: "campaign-1",
    entityName: "Q4 2024 Access Review",
    action: "task_completed",
    actor: "Sarah Chen",
    actorId: "user-1",
    timestamp: daysAgo(2),
    details: { decision: "approved", user: "Employee 12", app: "AWS" },
  },
  {
    id: "audit-5",
    entityType: "workflow",
    entityId: "wf-1",
    entityName: "Employee Onboarding",
    action: "workflow_run",
    actor: "System",
    actorId: "",
    timestamp: daysAgo(2),
    details: { status: "success", triggeredBy: "new_user" },
  },
  {
    id: "audit-6",
    entityType: "contract",
    entityId: "contract-3",
    entityName: "Salesforce Contract",
    action: "renewal_approaching",
    actor: "System",
    actorId: "",
    timestamp: daysAgo(5),
    details: { daysUntilRenewal: 15 },
  },
]

// Add more audit events for realism
for (let i = 7; i <= 30; i++) {
  const types: AuditEvent["entityType"][] = ["app", "user", "contract", "workflow", "access-review"]
  const type = types[i % types.length]
  const actions: Record<typeof type, string[]> = {
    app: ["status_changed", "owner_changed", "tag_added", "sso_enabled"],
    user: ["license_reclaimed", "access_granted", "access_revoked", "status_changed"],
    contract: ["renewal_approaching", "document_uploaded", "notes_updated"],
    workflow: ["workflow_run", "workflow_updated", "workflow_enabled"],
    "access-review": ["task_completed", "campaign_created", "reminder_sent"],
  }

  auditEvents.push({
    id: `audit-${i}`,
    entityType: type,
    entityId: `${type}-${(i % 5) + 1}`,
    entityName: `${type.charAt(0).toUpperCase() + type.slice(1)} ${(i % 5) + 1}`,
    action: actions[type][i % actions[type].length],
    actor: users[i % 8].name,
    actorId: users[i % 8].id,
    timestamp: daysAgo(i),
    details: {},
  })
}

// Departments
export const departmentsList: Department[] = departments.map((name, i) => ({
  id: `dept-${i + 1}`,
  name,
  costCenter: `CC-${1000 + i * 100}`,
  headcount: users.filter((u) => u.department === name).length,
  appCount: Math.floor(Math.random() * 10) + 5,
  monthlySpend: Math.floor(Math.random() * 50000) + 10000,
}))

// Risk Scoring Rules
export const riskScoringRules: RiskScoringRule[] = [
  { id: "rule-1", name: "No SSO Connected", weight: 30, enabled: true },
  { id: "rule-2", name: "High Admin Count", weight: 20, enabled: true },
  { id: "rule-3", name: "Sensitive Data Access", weight: 25, enabled: true },
  { id: "rule-4", name: "Low Utilization", weight: 15, enabled: true },
  { id: "rule-5", name: "Unsanctioned Status", weight: 10, enabled: true },
]

// Notification Preferences
export const notificationPreferences: NotificationPreference[] = [
  { id: "notif-1", type: "Renewal Reminders", email: true, slack: true, inApp: true },
  { id: "notif-2", type: "Access Review Due", email: true, slack: true, inApp: true },
  { id: "notif-3", type: "Shadow IT Detected", email: true, slack: true, inApp: true },
  { id: "notif-4", type: "Workflow Failures", email: true, slack: false, inApp: true },
  { id: "notif-5", type: "License Reclamation", email: false, slack: true, inApp: true },
]
